name: Run Selenium Script

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}/selenium-script:latest

    - name: Run container
      env:
        MIU_EMAIL: ${{ secrets.MIU_EMAIL }}
        MIU_PASSWORD: ${{ secrets.MIU_PASSWORD }}
      run: |
        docker run \
          -e MIU_EMAIL=$MIU_EMAIL \
          -e MIU_PASSWORD=$MIU_PASSWORD \
          ghcr.io/${{ github.repository }}/selenium-script:latest
