name: Run Selenium Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest

    env:
      MIU_EMAIL: ${{ secrets.MIU_EMAIL }}
      MIU_PASSWORD: ${{ secrets.MIU_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        sudo apt-get install -y unzip
        curl -sS -o chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        rm chromedriver_linux64.zip

    - name: Verify environment variables
      run: |
        echo "MIU_EMAIL: $MIU_EMAIL"
        echo "MIU_PASSWORD: $MIU_PASSWORD"

    - name: Run Selenium script
      run: |
        python script.py
