name: Job Search Report Automation

on:
  schedule:
    - cron: '0 3 * * *'  # Run at 3 AM UTC daily
  workflow_dispatch:      # Allow manual triggers

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest
    timeout-minutes: 15   # Add timeout
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.actor }}/selenium-script:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Create directories for artifacts
      run: |
        mkdir -p logs
        mkdir -p screenshots
        chmod 777 logs screenshots

    - name: Run container
      env:
        MIU_EMAIL: ${{ secrets.MIU_EMAIL }}
        MIU_PASSWORD: ${{ secrets.MIU_PASSWORD }}
      run: |
        docker run \
          --rm \
          -e MIU_EMAIL=$MIU_EMAIL \
          -e MIU_PASSWORD=$MIU_PASSWORD \
          -e TZ=America/Chicago \
          -v ${{ github.workspace }}/logs:/app/logs \
          -v ${{ github.workspace }}/screenshots:/app/screenshots \
          ghcr.io/${{ github.actor }}/selenium-script:latest

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: run-artifacts
        path: |
          logs/
          screenshots/
